# Generated by Django 5.1.7 on 2025-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_products_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_details',
            field=models.CharField(default='number', max_length=70),
            preserve_default=False,
        ),
    ]
