# Generated by Django 5.1.7 on 2025-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sale_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
