# Generated by Django 5.1.7 on 2025-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sale_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mode_of_payment',
            field=models.CharField(default='cash', max_length=20),
            preserve_default=False,
        ),
    ]
